const books = [
    "Ngôn ngữ cơ thể",
    "Nghệ thuật giao tiếp để thành công (nơi công sở)",
    "Giao tiếp bất kỳ ai",
    "Sức mạnh của ngôn từ",
    "5’ chinh phục người đối diện",
    "Đừng bao giờ đi ăn một mình",
    "Ai che lưng cho bạn",
    "Những đòn tâm lý trong thuyết phục",
    "Bạn có thể đàm phán bất cứ điều gì",
    "Bảy cấp độ giao tiếp để thành công",
    "Thôi miên bằng ngôn từ",
    "Đọc vị bất kỳ ai",
    "Lời từ chối hoàn hảo",
    "Kỹ năng nói chuyện với mọi người ở mọi nơi, mọi lúc",
    "Tử huyệt cảm xúc",
    "Nghệ thuật nói trước công chúng",
    "Hài hước một chút thế giới sẽ khác đi",
    "Nói nhiều không bằng nói đúng",
    "Nói thế nào để được chào đón, làm thế nào để được ghi nhận",
    "Kỹ năng giao tiếp đỉnh cao",
    "Tâm lý học nghệ thuật giao tiếp để thành công",
    "Năng lực giao tiếp",
    "Năng lực hài hước",
    "Nói chuyện là bản năng giữ miệng là tu dưỡng im lặng là trí tuệ",
    "Nghệ thuật thiết lập truyền thông",
    "Thuật xử thế của người xưa",
    "Học ăn học nói học gói học mở",
    "Nói một cách đơn giản",
    "Nói khác để sống khác",
    "Kỹ năng lắng nghe trong giao tiếp",
    "Văn hóa giao tiếp của người Nhật",
    "Thuật đọc nguội",
    "Thuật thôi miên trong giao tiếp",
    "Omoiyari - nghệ thuật đối nhân xử thế của người Nhật",
    "Mặc kệ thiên hạ sống như người Nhật",
    "Mình lá cá, việc của mình là bơi",
    "Nóng giận là bản năng, tĩnh lặng là bản lĩnh",
    "48 nguyên tắc chủ chốt của quyền lực",
    "Thao túng tâm lý",
    "Thuật thao túng",
    "Tại sao em ít nói thế",
    "Kết nối bất kỳ ai",
    "Quyến rũ phái đẹp bằng cả chân tình",
    "Tại sao đàn ông không biết lắng nghe và phụ nữ không biết đọc bản đồ - Cuộc chiến trong phòng ngủ",
    "Tại sao đàn ông thích tính dục và phụ nữ cần tình yêu",
    "5 ngôn ngữ yêu thương",
    "The way of the superior man",
    "Đàn ông sao Hỏa, đàn bà sao Kim",
    "Cư xử như đàn bà, suy nghĩ như đàn ông",
    "Tâm lý học hẹn hò – Nghệ thuật giao tiếp trong tình yêu",
    "Tán tỉnh bất kỳ ai",
    "Nghệ thuật quyến rũ",
    "Những điều phái nữ muốn nam giới biết",
    "Tâm lý học giải mã tình yêu",
    "Tâm lý học tình yêu Hàn",
    "Tâm lý học tình yêu Trung",
    "Chuyện tình yêu bạn biết bao nhiêu",
    "Một mình tìm một nửa",
    "Bạn là ai khi yêu",
    "Tại sao lại là người ấy",
    "Nghiệp tình yêu",
    "Hôn nhân chân kinh",
    "Bảy thói quen tạo gia đình hạnh phúc",
    "Làm cha mẹ tỉnh thức",
    "Gia đình tỉnh thức",
    "Cha mẹ độc hại",
    "Hai mặt của gia đình",
    "Ninja dọn dẹp",
    "8 Tố Chất Trí Tuệ Quyết Định Cuộc Đời Người Đàn Ông",
    "Thượng đế giấu đàn ông tốt đâu cả rồi",
    "Giải mã đàn ông",
    "Nói luôn cho nó vuông",
    "Bí mật của đàn ông",
    "Đàn ông nghĩ gì về phụ nữ",
    "Tâm lý học đàn ông",
    "Khoa Học Về Sự Hấp Dẫn",
    "Alpha Art",
    "20 Tuổi Quyết Định Cuộc Đời Người Đàn Ông",
    "Những quy tắc trong tình yêu",
    "Những quy tắc làm cha mẹ",
    "Hướng dẫn sử dụng nửa kia",
    "Bí mật đàn ông",
    "Năm ngôn ngữ tình yêu dành cho người ở một mình",
    "Năm ngôn ngữ tình yêu dành cho trẻ em",
    "Năm ngôn ngữ tình yêu dành cho bạn trẻ",
    "Bí quyết để có bạn đời lý tưởng",
    "Cây dù của bạn màu gì",
    "Trên đường băng",
    "Cà phê cùng Tony",
    "Nếu tôi biết được khi còn 20",
    "Dám mơ lớn, đừng hoài phí tuổi trẻ",
    "Bí quyết thành công sinh viên",
    "20 tuổi trở thành người biết nói, giỏi làm",
    "Học khôn ngoan mà không gian",
    "Bảy thói quen của bạn trẻ thành đạt",
    "Cảm xúc là kẻ thù số một của thành công",
    "Tuổi trẻ không trì hoãn",
    "Đời ngắn đừng ngủ dài",
    "Khởi hành",
    "Tôi tự học"
];

function displayBooks() {
    const bookList = document.getElementById('book-list');
    books.forEach((book, index) => {
        const li = document.createElement('li');
        li.textContent = `${index + 1}. ${book}`;
        bookList.appendChild(li);
    });
}

document.addEventListener('DOMContentLoaded', displayBooks);
